services:
  singbox-srs-generator:
    build:
      context: .
    container_name: singbox-srs-generator
    network_mode: bridge
    env_file:
      - ./mapping/config/.env
    ports:
      - "9044:9044"
    volumes:
      - ./app.py:/app/app.py
      - ./web:/app/web
      - ./mapping:/app/mapping
    restart: unless-stopped
