services:
  singbox-srs-generator:
    build:
      context: .
    container_name: singbox-srs-generator
    env_file:
      - ./config/.env
    ports:
      - "9044:9044"
    volumes:
      - ./rules:/app/rules
      - ./rules-dat:/app/rules-dat
      - ./rule-set:/app/rule-set
      - ./bin:/app/bin
      - ./config:/app/config
    restart: unless-stopped
